#!/usr/bin/env bash
set -eEo pipefail
cd opus

BUILD="build_$TARGET_TRIPLE"

if [ "$(dpkg --print-architecture)" != "$DPKG_ARCH" ]; then
  CROSS_COMPILING='1'
else
  CROSS_COMPILING=''
fi

if [ "$CROSS_COMPILING" == '1' ]; then
  CMAKE_TRY_COMPILE_TARGET_TYPE_OPTION='-DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY'
else
  CMAKE_TRY_COMPILE_TARGET_TYPE_OPTION=''
fi
CMAKE_C_FLAGS=(-fPIC)
echo "CMAKE_C_FLAGS: ${CMAKE_C_FLAGS[*]}"

cmake -B"$BUILD" \
"$CMAKE_TRY_COMPILE_TARGET_TYPE_OPTION" \
-DBUILD_SHARED_LIBS=off \
-DOPUS_BUILD_SHARED_LIBRARY=off \
-DOPUS_BUILD_PROGRAMS=off \
-DOPUS_BUILD_TESTING=off \
-DCMAKE_C_FLAGS="${CMAKE_C_FLAGS[*]}" \
-DCMAKE_TOOLCHAIN_FILE="$TOOLCHAIN_FILE"